sudo: required
dist: trusty

language: node_js
node:
  - 12

jobs:
  include:
    - name: "macOS"
      os: osx
      osx_image: "xcode11.3"
      script:
        - electron-builder --publish=onTagOrDraft

    - name: "Windows"
      os: osx
      osx_image: "xcode11.3"
      script:
        - electron-builder --windows portable --x64 --publish=onTagOrDraft -c.productName='Blockbench_portable'
        - electron-builder -w --ia32 --x64 --publish=onTagOrDraft

    - name: "Linux"
      os: linux
      script:
        - sudo apt-get install rpm
        - electron-builder --publish=onTagOrDraft


cache:
  directories:
    - node_modules

install:
  - npm install

notifications:
  email: false