sudo: required
dist: trusty

language: node_js

jobs:
  include:
    - name: "macOS + Win Portable"
      os: osx
      script:
        - electron-builder --publish=always
        - electron-builder --windows portable --x64 --publish=always -c.productName='Blockbench_portable'

    - name: "Windows"
      os: osx
      script:
        - electron-builder -w --x64 --publish=always
        - electron-builder -w --ia32 --publish=always -c.productName='Blockbench_32bit'
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        file: dist/win-unpacked/resources/app.asar

    - name: "Linux"
      os: linux
      script:
        - sudo apt-get install rpm
        - electron-builder --publish=always


cache:
  directories:
    - node_modules

install:
  - nvm install 12.17.0
  - npm install electron-builder

notifications:
  email: false