blank_issues_enabled: false
contact_links:
  - name: Plugin Issue / Suggestion
    url: https://github.com/JannisX11/blockbench-plugins
    about: Please report issues or feedback related to Blockbench plugins on the Plugins repository.
  - name: Modeling Help / Support
    url: http://discord.blockbench.net
    about: If you need help with modeling or implementing models into your project, please ask on the Discord server instead of opening an issue.